version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./Kiddy.Web/Kiddy.Web.csproj
      - run: dotnet build ./Kiddy.Web/Kiddy.Web.csproj
