version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/aspnet:3.0
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore ./Kiddy.Web/Kiddy.Web.csproj
      - run: dotnet build ./Kiddy.Web/Kiddy.Web.csproj
